<?php

declare(strict_types=1);

namespace Hirtz\Cms\Shopify\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000600CmsShopifyBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD `product_id` bigint(20) unsigned NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD UNIQUE KEY `product_id` (`product_id`)
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD CONSTRAINT `entry_product_id_ibfk` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
